[workspace]
resolver = "2"
members = ["projects/*"]
default-members = [
    "projects/parallel",
]
exclude = [
    "projects/.DS_Store",
    "projects/image",
]

[profile.release]
lto = true
panic = "abort"
